<?php
/**
 * Convites Marciano & Marta — slug na URL => nome na Fase 2.
 */
return [
    'pai-feliciano-mae-rosa' => 'Pai Feliciano e Mãe Rosa',
    'celeste-elsinha' => 'Celeste e Elsinha',
    'arsenio-airosa' => 'Arsénio e Airosa',
    'dorcas-anselmo' => 'Dorca e Anselmo',
    'anencia-fernando' => 'Anência e Fernando',
    'jacinto-bia' => 'Jacinto e Bia',
    'cecilia-helena' => 'Cecilia e Helena',
    'manuel-paula' => 'Manuel e Paula',
    'mapedjissane-esposa' => 'Mapedjissane e Esposa',
    'gloria-lau' => 'Gloria e Lau',
    'argentina-elisa' => 'Argentina e Elisa',
    'fatima-ondina' => 'Fatima e Ondina',
    'pedro-assucenia' => 'Pedro e Assucenia',
    'belinda-esposo' => 'Belinda e esposo',
    'auria-esposo' => 'Auria e esposo',
    'lourenco-yolanda' => 'Lourenço e Yolanda',
    'odete-melita' => 'Odete e Melita',
    'baptista-faura' => 'Baptista e Fáura',
    'helio-dina' => 'Hélio e Dina',
    'antonio-rosa' => 'António e Rosa',
    'tinga-esposa' => 'Tinga e Esposa',
    'sara-esposo' => 'Sara e esposo',
    'vovo-ernesto-vovo-marta' => 'Vovó Ernesto e Vovó Marta',
    'tia-poculucha-tia-martinha' => 'Tia poculucha e tia Martinha',
    'pai-pedro-mae-aldasse' => 'Pai Pedro e Mãe Aldasse',
    'tia-benilde-tia-artimiza' => 'Tia Benilde e Tia Artimiza',
    'joyce-esposo' => 'Joyce e esposo',
    'zaida-esposo' => 'Zaida e esposo',
    'amelia-esposo' => 'Amélia e esposo',
    'mana-dercia-zinha' => 'Mana Dércia e Zinha',
    'tia-celia-esposo' => 'Tia Célia e esposo',
    'daiana-celinha' => 'Daiana e Celinha',
    'olivia-susu' => 'Olívia e Susú',
    'salmina-cintia' => 'Salmina e Cíntia',
    'tia-mira-dercio' => 'Tia Mira e Dercio',
    'tio-alberto-esposa' => 'Tio Alberto e esposa',
    'tio-rogero-esposa' => 'Tio Rogéro e esposa',
    'ambrosio-naife' => 'Ambrósio e Naife',
];
